Repository sparcs-kaist/taxi-app, pull requests merged in 2023-09, with the labels that each got.

#69 Fix: Remove error Code Check
  android/build.gradle
  lib/views/taxiView.dart
Labels: bug

#74 #72 bug taxi request origin header
  android/app/src/main/kotlin/com/example/taxi_app/MainActivity.kt
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/utils/fcmToken.dart
  lib/utils/remoteConfigController.dart
  lib/utils/token.dart
  lib/views/taxiView.dart
Labels: bug

#71 taxiDialog 리팩토링
  lib/constants/theme.dart
  lib/main.dart
  lib/views/taxiDialog.dart
  lib/views/taxiView.dart
Labels: enhancement

#76 Add: package for deep link
  android/app/src/main/AndroidManifest.xml
  lib/views/taxiView.dart
  pubspec.yaml
Labels: bug, enhancement

#83 Fix: taxiDialog button expanded
  lib/constants/theme.dart
  lib/views/taxiDialog.dart
Labels: bug

#81 Refactor: Change Cookie URL
  ios/Runner/Info.plist
  lib/views/taxiView.dart
  pubspec.yaml
Labels: bug

#78 InAppNotification
  lib/constants/theme.dart
  lib/main.dart
  lib/views/taxiView.dart
Labels: enhancement

#86 #85 inappNoti Fix
  .env.example
  lib/constants/theme.dart
  lib/views/taxiView.dart
Labels: bug, enhancement
